# Generated by Django 2.2.11 on 2023-12-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='info',
        ),
        migrations.RemoveField(
            model_name='student',
            name='info',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='info',
        ),
    ]
