# Generated by Django 2.2.11 on 2024-01-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.IntegerField(choices=[(1, '第一节'), (2, '第二节'), (3, '第三节'), (4, '第四节'), (5, '第五节'), (6, '第六节'), (7, '第七节'), (8, '第八节')], default=1, verbose_name='结尾时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.IntegerField(choices=[(1, '第一节'), (2, '第二节'), (3, '第三节'), (4, '第四节'), (5, '第五节'), (6, '第六节'), (7, '第七节'), (8, '第八节')], default=1, verbose_name='开始时间'),
        ),
    ]
